### ISSUE TITLE
About the export format

### ISSUE THREAD

**Issue by LuxiMh** [r-ex/rsx#3]
Can I export game assets to obj format directly with this software?because I really bad to use the model file in cast format

**Comment by biast12** [comment]
just use cast https://github.com/dtzxporter/cast/releases

**Comment by focss** [comment]
> just use cast https://github.com/dtzxporter/cast/releases

I use this pulgin for Blender to open cast format exported by your software, but only point cloud data (without geometry) is visible.

**Comment by focss** [comment]
> > just use cast https://github.com/dtzxporter/cast/releases
> 
> I use this pulgin for Blender to open cast format exported by your software, but only point cloud data (without geometry) is visible.

This plugin works only in blender english version, and apex_auto_tex plugin is required.

**Comment by r-ex** [comment]
> Can I export game assets to obj format directly with this software?because I really bad to use the model file in cast format

sorry for the late reply
currently only CAST, RMAX, and RMDL are supported by RSX (selectable by the "Export Options" tab in the menu bar at the top of the RSX window)

while OBJ is planned to be added in the future, I would recommend trying to use Cast if possible.
the Cast model format is able to contain more information about the model than OBJ can, and will likely result in the model being easier to use in software such as Blender and Maya.

RMAX is a custom format that was made for this tool, however the plugin to use it in Blender is not currently available, so this format is not usable
RMDL is the format that the game itself uses, and (as far as i am aware) is not directly importable into any external 3D software
