### ISSUE TITLE
The asset list doesn't seem to be in chronological order (it seems to order uppercase before lowercase)

### ISSUE THREAD

**Issue by biast12** [r-ex/rsx#4]
![image](https://github.com/r-ex/rsx/assets/53872542/cfcf32ec-4fb5-4c96-bb21-9c76534f57f6)

**Comment by IJARika** [comment]
I'm not sure what you mean by chronological in this context, legion's asset list order just mirrors the pak's asset list. RSX uses alphabetically on purpose, it's much easier for a person to trawl through it in this form.

**Comment by biast12** [comment]
What i mean is the fact that it takes uppercase characters before the lowercase characters = it's not actually in alphabetical order (what i meant with chronological)

For an example in the image is "mdl\Weapons\..." before "mdl\angel_city"
here is another example, when loading all rpaks (minus startup_early.rpak), this is the top of the list, all uppercase characters  
![image](https://github.com/r-ex/rsx/assets/53872542/2a101715-47ce-4b7b-ae5f-ab882d1485dc)

looks like the real order is: uppercase => special characters => lowercase 

Also agree with you it's much easier for people to know where things are if they're in alphabetically order = why i reported it

**Comment by r-ex** [comment]
this should be fixed in release [1.0.1-beta1](https://github.com/r-ex/rsx/releases/tag/1.0.1-beta1) (including the ability to sort by different columns)
