### ISSUE TITLE
(Request) Remove duplicated assets from the Asset List

### ISSUE THREAD

**Issue by biast12** [r-ex/rsx#6]
There's a lot of duplicated assets in the Asset List, it does fill quite a lot at time, would love if we only had one of each name

![image](https://github.com/r-ex/rsx/assets/53872542/4ac4a817-c027-4351-b371-61ecee0429f4)
![image](https://github.com/r-ex/rsx/assets/53872542/594ea1a6-74db-41fa-a094-11254a945e0f)

**Comment by IJARika** [comment]
handled as of release [1.0.1-beta1](https://github.com/r-ex/rsx/releases/tag/1.0.1-beta1), with the asset's pak being shown.
